# this is for testing on local env heroku will build from Dockerfile
version: "3"
services:
  short-url-server:
    restart: always
    container_name: "server"
    build: .
    ports:
      - "5500:5500"
    depends_on:
      - "db"
  db:
    image: mongo
    restart: always
    container_name: "db"
    ports:
      - "27017:27017"
    volumes:
      - ./temp-data:/data/db # please remove the temp-data directory when done testing
volumes:
  temp-data:
